var hierarchy =
[
    [ "_USB_CONFIG_DEscriptOR", "struct__USB__CONFIG__DEscriptOR.html", null ],
    [ "_USB_CONFIG_DEscriptOR_LONG", "struct__USB__CONFIG__DEscriptOR__LONG.html", null ],
    [ "_USB_DEVICE_DEscriptOR", "struct__USB__DEVICE__DEscriptOR.html", null ],
    [ "_USB_ENDPOINT_DEscriptOR", "struct__USB__ENDPOINT__DEscriptOR.html", null ],
    [ "_USB_INTERF_DEscriptOR", "struct__USB__INTERF__DEscriptOR.html", null ],
    [ "Cmd_list_tab_type", "structCmd__list__tab__type.html", null ],
    [ "Compass_Calibration_Parameter", "structCompass__Calibration__Parameter.html", null ],
    [ "cRGB", "structcRGB.html", null ],
    [ "EEPROMClass", "structEEPROMClass.html", null ],
    [ "EEPtr", "structEEPtr.html", null ],
    [ "EERef", "structEERef.html", null ],
    [ "Encoder_port_type", "structEncoder__port__type.html", null ],
    [ "irparams_t", "structirparams__t.html", null ],
    [ "LED_Matrix_Clock_Number_Font_3x8_TypeDef", "structLED__Matrix__Clock__Number__Font__3x8__TypeDef.html", null ],
    [ "LED_Matrix_Font_6x8_TypeDef", "structLED__Matrix__Font__6x8__TypeDef.html", null ],
    [ "Me_Encoder_type", "structMe__Encoder__type.html", null ],
    [ "Mecolor", "classMecolor.html", null ],
    [ "MeEncoderNew", "classMeEncoderNew.html", null ],
    [ "MeEncoderOnBoard", "classMeEncoderOnBoard.html", null ],
    [ "megapi_dc_type", "structmegapi__dc__type.html", null ],
    [ "megaPi_slot", "structmegaPi__slot.html", null ],
    [ "megapipro_esc_type", "structmegapipro__esc__type.html", null ],
    [ "MeHostParser", "classMeHostParser.html", null ],
    [ "MeIR", "classMeIR.html", null ],
    [ "MeMegaPiDCMotor", "classMeMegaPiDCMotor.html", null ],
    [ "MeMegaPiProESCMotor", "classMeMegaPiProESCMotor.html", null ],
    [ "MeOneWire", "classMeOneWire.html", null ],
    [ "MePort", "classMePort.html", [
      [ "Me4Button", "classMe4Button.html", null ],
      [ "Me7SegmentDisplay", "classMe7SegmentDisplay.html", null ],
      [ "MeBuzzer", "classMeBuzzer.html", null ],
      [ "MeColorSensor", "classMeColorSensor.html", null ],
      [ "MeCompass", "classMeCompass.html", null ],
      [ "MeDCMotor", "classMeDCMotor.html", [
        [ "MBotDCMotor", "classMBotDCMotor.html", null ]
      ] ],
      [ "MeEncoderMotor", "classMeEncoderMotor.html", null ],
      [ "MeFlameSensor", "classMeFlameSensor.html", null ],
      [ "MeGasSensor", "classMeGasSensor.html", null ],
      [ "MeGyro", "classMeGyro.html", null ],
      [ "MeHumiture", "classMeHumiture.html", null ],
      [ "MeJoystick", "classMeJoystick.html", null ],
      [ "MeLEDMatrix", "classMeLEDMatrix.html", null ],
      [ "MeLightSensor", "classMeLightSensor.html", null ],
      [ "MeLimitSwitch", "classMeLimitSwitch.html", null ],
      [ "MeLineFollower", "classMeLineFollower.html", null ],
      [ "MeMegaPiPro4DcMotor", "classMeMegaPiPro4DcMotor.html", null ],
      [ "MeOnBoardTemp", "classMeOnBoardTemp.html", null ],
      [ "MePIRMotionSensor", "classMePIRMotionSensor.html", null ],
      [ "MePotentiometer", "classMePotentiometer.html", null ],
      [ "MeRGBLed", "classMeRGBLed.html", null ],
      [ "MeSerial", "classMeSerial.html", [
        [ "MeBluetooth", "classMeBluetooth.html", null ],
        [ "MeInfraredReceiver", "classMeInfraredReceiver.html", null ],
        [ "MePS2", "classMePS2.html", null ],
        [ "MePm25Sensor", "classMePm25Sensor.html", null ],
        [ "MeSmartServo", "classMeSmartServo.html", null ],
        [ "MeVoice", "classMeVoice.html", null ],
        [ "MeWifi", "classMeWifi.html", null ]
      ] ],
      [ "MeShutter", "classMeShutter.html", null ],
      [ "MeSoundSensor", "classMeSoundSensor.html", null ],
      [ "MeStepper", "classMeStepper.html", null ],
      [ "MeTemperature", "classMeTemperature.html", null ],
      [ "MeTouchSensor", "classMeTouchSensor.html", null ],
      [ "MeUSBHost", "classMeUSBHost.html", null ],
      [ "MeUltrasonicSensor", "classMeUltrasonicSensor.html", null ]
    ] ],
    [ "MePort_Sig", "structMePort__Sig.html", null ],
    [ "MePressureSensor", "classMePressureSensor.html", null ],
    [ "MeStepperOnBoard", "classMeStepperOnBoard.html", null ],
    [ "PID_internal", "structPID__internal.html", null ],
    [ "PM25DATASTRUCT", "structPM25DATASTRUCT.html", null ],
    [ "PM25DATAUINO", "unionPM25DATAUINO.html", null ],
    [ "Servo", "classServo.html", null ],
    [ "servo_device_type", "structservo__device__type.html", null ],
    [ "servo_t", "structservo__t.html", null ],
    [ "ServoPin_t", "structServoPin__t.html", null ],
    [ "SPIClass", "classSPIClass.html", null ],
    [ "SPISettings", "classSPISettings.html", null ],
    [ "Stream", null, [
      [ "SoftwareSerial", "classSoftwareSerial.html", [
        [ "MeSerial", "classMeSerial.html", null ]
      ] ],
      [ "TwoWire", "classTwoWire.html", null ]
    ] ],
    [ "sysex_message", "unionsysex__message.html", null ],
    [ "sysex_message_type", "structsysex__message__type.html", null ]
];